# general configuration
url: https://deekayen.net
baseurl: ''

# compass configuration
compass:
  # author will appear under the avatar (optional)
  author: "David Norman"
  # tagline will appear under the title (optional)
  tagline: "Technologist and Scouter"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "etowahscouting"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
