# Site settings
title: "David Norman, Ph.D."
description: "Resume for David Norman, IT Engineer, Georgia, USA"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "David Norman, Ph.D."
resume_title:                   "Platform Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "david@dkn.email"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_address:         "Georgia, USA"

resume_header_contact_info:     "Georgia USA â€¢ david@dkn.email"
display_header_contact_info:    "false"

resume_header_intro: >
  <p>I manage <a href="https://aws.amazon.com/">AWS</a> cloud server infrastructure.</p>

  <h3>Previously</h3>
  <p>Application configuration, web application architecture and deployment, IT management, and <a href="https://www.drupal.org/user/972">Drupal development</a>. I'm also the author of the <a href="https://normanlayout.info">Norman keyboard layout</a> and discoverer of the prime number <a href="https://www.primegrid.com/primes/?section=primelist&userid=75896">366216162^65536+1</a>.</p>

  <h3>Personality profile</h3>
  <p>Using misc personality profiles, I'm an <a href="https://www.16personalities.com/intp-personality">INTP</a>, a <em>C</em> in the <a href="https://www.discprofile.com/disc-styles/conscientiousness">DiSC profile</a>, and Enneagram <a href="https://enneagramuniverse.com/enneagram/learn/enneagram-wings/enneagram_5w4">Type 5w4: The Iconoclast</a>.</p>


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/deekayen"
#  resume_linkedin_url:          "https://www.linkedin.com/in/deekayen"
#  resume_website_url:           "https://deekayen.com"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
